// flow-typed signature: b55cc15e3bee9515277fe8b09dff715a
// flow-typed version: <<STUB>>/@types/jest_v^20.0.8/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/jest' {
  declare module.exports: any;
}
