// flow-typed signature: 281663b6d45229144749d8fa21d60b06
// flow-typed version: <<STUB>>/rambda_v^0.8.7/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rambda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rambda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rambda/__tests__/addIndex' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/adjust' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/any' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/append' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/filter' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/find' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/findIndex' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/flatten' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/indexOf' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/join' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/map' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/prepend' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/range' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/reduce' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/array/update' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/contains' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/drop' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/dropLast' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/head' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/includes' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/init' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/last' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/concat' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/endsWith' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/lastIndexOf' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/length' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/not' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/padEnd' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/padStart' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/reverse' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/startsWith' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/toLower' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/toString' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/toUpper' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/lazy/trim' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/all' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/allPass' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/always' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/both' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/complement' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/compose' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/curry' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/defaultTo' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/either' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/equals' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/identity' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/ifElse' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/logic/partialCurry' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/match' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/add' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/divide' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/modulo' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/multiply' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/math/subtract' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/merge' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/has' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/omit' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/path' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/pick' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/pluck' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/prop' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/object/values' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/other' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/propEq' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/repeat' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/replace' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/sort' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/sortBy' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/split' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/splitEvery' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/tail' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/take' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/takeLast' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/tap' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/test' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/type' {
  declare module.exports: any;
}

declare module 'rambda/__tests__/uniq' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/add' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/adjust' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/any' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/append' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/compose' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/contains' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/drop' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/dropLast' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/equals' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/filter' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/find' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/findIndex' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/flatten' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/head' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/headString' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/index' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/indexOf' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/init' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/initString' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/last' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/map' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/match' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/merge' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/omit' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/path' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/pick' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/prop' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/propEq' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/range' {
  declare module.exports: any;
}

declare module 'rambda/benchmarks/reduce' {
  declare module.exports: any;
}

declare module 'rambda/files/benchmark' {
  declare module.exports: any;
}

declare module 'rambda/files/browseByTag' {
  declare module.exports: any;
}

declare module 'rambda/files/lint' {
  declare module.exports: any;
}

declare module 'rambda/files/rollup.config' {
  declare module.exports: any;
}

declare module 'rambda/modules/addIndex' {
  declare module.exports: any;
}

declare module 'rambda/modules/adjust' {
  declare module.exports: any;
}

declare module 'rambda/modules/all' {
  declare module.exports: any;
}

declare module 'rambda/modules/allPass' {
  declare module.exports: any;
}

declare module 'rambda/modules/any' {
  declare module.exports: any;
}

declare module 'rambda/modules/append' {
  declare module.exports: any;
}

declare module 'rambda/modules/both' {
  declare module.exports: any;
}

declare module 'rambda/modules/compose' {
  declare module.exports: any;
}

declare module 'rambda/modules/contains' {
  declare module.exports: any;
}

declare module 'rambda/modules/curry' {
  declare module.exports: any;
}

declare module 'rambda/modules/defaultTo' {
  declare module.exports: any;
}

declare module 'rambda/modules/drop' {
  declare module.exports: any;
}

declare module 'rambda/modules/dropLast' {
  declare module.exports: any;
}

declare module 'rambda/modules/either' {
  declare module.exports: any;
}

declare module 'rambda/modules/equals' {
  declare module.exports: any;
}

declare module 'rambda/modules/filter' {
  declare module.exports: any;
}

declare module 'rambda/modules/find' {
  declare module.exports: any;
}

declare module 'rambda/modules/findIndex' {
  declare module.exports: any;
}

declare module 'rambda/modules/flatten' {
  declare module.exports: any;
}

declare module 'rambda/modules/has' {
  declare module.exports: any;
}

declare module 'rambda/modules/head' {
  declare module.exports: any;
}

declare module 'rambda/modules/ifElse' {
  declare module.exports: any;
}

declare module 'rambda/modules/indexOf' {
  declare module.exports: any;
}

declare module 'rambda/modules/init' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/baseSlice' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/curry' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/curryThree' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/helper' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/mathHelper' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/oppositeHelper' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/passingHelper' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/propHelper' {
  declare module.exports: any;
}

declare module 'rambda/modules/internal/simpleHelper' {
  declare module.exports: any;
}

declare module 'rambda/modules/last' {
  declare module.exports: any;
}

declare module 'rambda/modules/map' {
  declare module.exports: any;
}

declare module 'rambda/modules/match' {
  declare module.exports: any;
}

declare module 'rambda/modules/merge' {
  declare module.exports: any;
}

declare module 'rambda/modules/omit' {
  declare module.exports: any;
}

declare module 'rambda/modules/partialCurry' {
  declare module.exports: any;
}

declare module 'rambda/modules/path' {
  declare module.exports: any;
}

declare module 'rambda/modules/pick' {
  declare module.exports: any;
}

declare module 'rambda/modules/pluck' {
  declare module.exports: any;
}

declare module 'rambda/modules/prepend' {
  declare module.exports: any;
}

declare module 'rambda/modules/prop' {
  declare module.exports: any;
}

declare module 'rambda/modules/propEq' {
  declare module.exports: any;
}

declare module 'rambda/modules/range' {
  declare module.exports: any;
}

declare module 'rambda/modules/reduce' {
  declare module.exports: any;
}

declare module 'rambda/modules/repeat' {
  declare module.exports: any;
}

declare module 'rambda/modules/replace' {
  declare module.exports: any;
}

declare module 'rambda/modules/sort' {
  declare module.exports: any;
}

declare module 'rambda/modules/sortBy' {
  declare module.exports: any;
}

declare module 'rambda/modules/split' {
  declare module.exports: any;
}

declare module 'rambda/modules/splitEvery' {
  declare module.exports: any;
}

declare module 'rambda/modules/tail' {
  declare module.exports: any;
}

declare module 'rambda/modules/take' {
  declare module.exports: any;
}

declare module 'rambda/modules/takeLast' {
  declare module.exports: any;
}

declare module 'rambda/modules/tap' {
  declare module.exports: any;
}

declare module 'rambda/modules/testFn' {
  declare module.exports: any;
}

declare module 'rambda/modules/type' {
  declare module.exports: any;
}

declare module 'rambda/modules/uniq' {
  declare module.exports: any;
}

declare module 'rambda/modules/update' {
  declare module.exports: any;
}

declare module 'rambda/modules/values' {
  declare module.exports: any;
}

declare module 'rambda/rambda' {
  declare module.exports: any;
}

declare module 'rambda/webVersion' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rambda/__tests__/addIndex.js' {
  declare module.exports: $Exports<'rambda/__tests__/addIndex'>;
}
declare module 'rambda/__tests__/array/adjust.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/adjust'>;
}
declare module 'rambda/__tests__/array/any.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/any'>;
}
declare module 'rambda/__tests__/array/append.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/append'>;
}
declare module 'rambda/__tests__/array/filter.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/filter'>;
}
declare module 'rambda/__tests__/array/find.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/find'>;
}
declare module 'rambda/__tests__/array/findIndex.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/findIndex'>;
}
declare module 'rambda/__tests__/array/flatten.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/flatten'>;
}
declare module 'rambda/__tests__/array/indexOf.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/indexOf'>;
}
declare module 'rambda/__tests__/array/join.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/join'>;
}
declare module 'rambda/__tests__/array/map.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/map'>;
}
declare module 'rambda/__tests__/array/prepend.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/prepend'>;
}
declare module 'rambda/__tests__/array/range.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/range'>;
}
declare module 'rambda/__tests__/array/reduce.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/reduce'>;
}
declare module 'rambda/__tests__/array/update.js' {
  declare module.exports: $Exports<'rambda/__tests__/array/update'>;
}
declare module 'rambda/__tests__/contains.js' {
  declare module.exports: $Exports<'rambda/__tests__/contains'>;
}
declare module 'rambda/__tests__/drop.js' {
  declare module.exports: $Exports<'rambda/__tests__/drop'>;
}
declare module 'rambda/__tests__/dropLast.js' {
  declare module.exports: $Exports<'rambda/__tests__/dropLast'>;
}
declare module 'rambda/__tests__/head.js' {
  declare module.exports: $Exports<'rambda/__tests__/head'>;
}
declare module 'rambda/__tests__/includes.js' {
  declare module.exports: $Exports<'rambda/__tests__/includes'>;
}
declare module 'rambda/__tests__/init.js' {
  declare module.exports: $Exports<'rambda/__tests__/init'>;
}
declare module 'rambda/__tests__/last.js' {
  declare module.exports: $Exports<'rambda/__tests__/last'>;
}
declare module 'rambda/__tests__/lazy/concat.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/concat'>;
}
declare module 'rambda/__tests__/lazy/endsWith.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/endsWith'>;
}
declare module 'rambda/__tests__/lazy/lastIndexOf.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/lastIndexOf'>;
}
declare module 'rambda/__tests__/lazy/length.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/length'>;
}
declare module 'rambda/__tests__/lazy/not.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/not'>;
}
declare module 'rambda/__tests__/lazy/padEnd.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/padEnd'>;
}
declare module 'rambda/__tests__/lazy/padStart.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/padStart'>;
}
declare module 'rambda/__tests__/lazy/reverse.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/reverse'>;
}
declare module 'rambda/__tests__/lazy/startsWith.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/startsWith'>;
}
declare module 'rambda/__tests__/lazy/toLower.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/toLower'>;
}
declare module 'rambda/__tests__/lazy/toString.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/toString'>;
}
declare module 'rambda/__tests__/lazy/toUpper.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/toUpper'>;
}
declare module 'rambda/__tests__/lazy/trim.js' {
  declare module.exports: $Exports<'rambda/__tests__/lazy/trim'>;
}
declare module 'rambda/__tests__/logic/all.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/all'>;
}
declare module 'rambda/__tests__/logic/allPass.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/allPass'>;
}
declare module 'rambda/__tests__/logic/always.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/always'>;
}
declare module 'rambda/__tests__/logic/both.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/both'>;
}
declare module 'rambda/__tests__/logic/complement.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/complement'>;
}
declare module 'rambda/__tests__/logic/compose.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/compose'>;
}
declare module 'rambda/__tests__/logic/curry.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/curry'>;
}
declare module 'rambda/__tests__/logic/defaultTo.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/defaultTo'>;
}
declare module 'rambda/__tests__/logic/either.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/either'>;
}
declare module 'rambda/__tests__/logic/equals.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/equals'>;
}
declare module 'rambda/__tests__/logic/identity.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/identity'>;
}
declare module 'rambda/__tests__/logic/ifElse.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/ifElse'>;
}
declare module 'rambda/__tests__/logic/partialCurry.js' {
  declare module.exports: $Exports<'rambda/__tests__/logic/partialCurry'>;
}
declare module 'rambda/__tests__/match.js' {
  declare module.exports: $Exports<'rambda/__tests__/match'>;
}
declare module 'rambda/__tests__/math/add.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/add'>;
}
declare module 'rambda/__tests__/math/divide.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/divide'>;
}
declare module 'rambda/__tests__/math/modulo.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/modulo'>;
}
declare module 'rambda/__tests__/math/multiply.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/multiply'>;
}
declare module 'rambda/__tests__/math/subtract.js' {
  declare module.exports: $Exports<'rambda/__tests__/math/subtract'>;
}
declare module 'rambda/__tests__/merge.js' {
  declare module.exports: $Exports<'rambda/__tests__/merge'>;
}
declare module 'rambda/__tests__/object/has.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/has'>;
}
declare module 'rambda/__tests__/object/omit.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/omit'>;
}
declare module 'rambda/__tests__/object/path.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/path'>;
}
declare module 'rambda/__tests__/object/pick.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/pick'>;
}
declare module 'rambda/__tests__/object/pluck.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/pluck'>;
}
declare module 'rambda/__tests__/object/prop.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/prop'>;
}
declare module 'rambda/__tests__/object/values.js' {
  declare module.exports: $Exports<'rambda/__tests__/object/values'>;
}
declare module 'rambda/__tests__/other.js' {
  declare module.exports: $Exports<'rambda/__tests__/other'>;
}
declare module 'rambda/__tests__/propEq.js' {
  declare module.exports: $Exports<'rambda/__tests__/propEq'>;
}
declare module 'rambda/__tests__/repeat.js' {
  declare module.exports: $Exports<'rambda/__tests__/repeat'>;
}
declare module 'rambda/__tests__/replace.js' {
  declare module.exports: $Exports<'rambda/__tests__/replace'>;
}
declare module 'rambda/__tests__/sort.js' {
  declare module.exports: $Exports<'rambda/__tests__/sort'>;
}
declare module 'rambda/__tests__/sortBy.js' {
  declare module.exports: $Exports<'rambda/__tests__/sortBy'>;
}
declare module 'rambda/__tests__/split.js' {
  declare module.exports: $Exports<'rambda/__tests__/split'>;
}
declare module 'rambda/__tests__/splitEvery.js' {
  declare module.exports: $Exports<'rambda/__tests__/splitEvery'>;
}
declare module 'rambda/__tests__/tail.js' {
  declare module.exports: $Exports<'rambda/__tests__/tail'>;
}
declare module 'rambda/__tests__/take.js' {
  declare module.exports: $Exports<'rambda/__tests__/take'>;
}
declare module 'rambda/__tests__/takeLast.js' {
  declare module.exports: $Exports<'rambda/__tests__/takeLast'>;
}
declare module 'rambda/__tests__/tap.js' {
  declare module.exports: $Exports<'rambda/__tests__/tap'>;
}
declare module 'rambda/__tests__/test.js' {
  declare module.exports: $Exports<'rambda/__tests__/test'>;
}
declare module 'rambda/__tests__/type.js' {
  declare module.exports: $Exports<'rambda/__tests__/type'>;
}
declare module 'rambda/__tests__/uniq.js' {
  declare module.exports: $Exports<'rambda/__tests__/uniq'>;
}
declare module 'rambda/benchmarks/add.js' {
  declare module.exports: $Exports<'rambda/benchmarks/add'>;
}
declare module 'rambda/benchmarks/adjust.js' {
  declare module.exports: $Exports<'rambda/benchmarks/adjust'>;
}
declare module 'rambda/benchmarks/any.js' {
  declare module.exports: $Exports<'rambda/benchmarks/any'>;
}
declare module 'rambda/benchmarks/append.js' {
  declare module.exports: $Exports<'rambda/benchmarks/append'>;
}
declare module 'rambda/benchmarks/compose.js' {
  declare module.exports: $Exports<'rambda/benchmarks/compose'>;
}
declare module 'rambda/benchmarks/contains.js' {
  declare module.exports: $Exports<'rambda/benchmarks/contains'>;
}
declare module 'rambda/benchmarks/drop.js' {
  declare module.exports: $Exports<'rambda/benchmarks/drop'>;
}
declare module 'rambda/benchmarks/dropLast.js' {
  declare module.exports: $Exports<'rambda/benchmarks/dropLast'>;
}
declare module 'rambda/benchmarks/equals.js' {
  declare module.exports: $Exports<'rambda/benchmarks/equals'>;
}
declare module 'rambda/benchmarks/filter.js' {
  declare module.exports: $Exports<'rambda/benchmarks/filter'>;
}
declare module 'rambda/benchmarks/find.js' {
  declare module.exports: $Exports<'rambda/benchmarks/find'>;
}
declare module 'rambda/benchmarks/findIndex.js' {
  declare module.exports: $Exports<'rambda/benchmarks/findIndex'>;
}
declare module 'rambda/benchmarks/flatten.js' {
  declare module.exports: $Exports<'rambda/benchmarks/flatten'>;
}
declare module 'rambda/benchmarks/head.js' {
  declare module.exports: $Exports<'rambda/benchmarks/head'>;
}
declare module 'rambda/benchmarks/headString.js' {
  declare module.exports: $Exports<'rambda/benchmarks/headString'>;
}
declare module 'rambda/benchmarks/index.js' {
  declare module.exports: $Exports<'rambda/benchmarks/index'>;
}
declare module 'rambda/benchmarks/indexOf.js' {
  declare module.exports: $Exports<'rambda/benchmarks/indexOf'>;
}
declare module 'rambda/benchmarks/init.js' {
  declare module.exports: $Exports<'rambda/benchmarks/init'>;
}
declare module 'rambda/benchmarks/initString.js' {
  declare module.exports: $Exports<'rambda/benchmarks/initString'>;
}
declare module 'rambda/benchmarks/last.js' {
  declare module.exports: $Exports<'rambda/benchmarks/last'>;
}
declare module 'rambda/benchmarks/map.js' {
  declare module.exports: $Exports<'rambda/benchmarks/map'>;
}
declare module 'rambda/benchmarks/match.js' {
  declare module.exports: $Exports<'rambda/benchmarks/match'>;
}
declare module 'rambda/benchmarks/merge.js' {
  declare module.exports: $Exports<'rambda/benchmarks/merge'>;
}
declare module 'rambda/benchmarks/omit.js' {
  declare module.exports: $Exports<'rambda/benchmarks/omit'>;
}
declare module 'rambda/benchmarks/path.js' {
  declare module.exports: $Exports<'rambda/benchmarks/path'>;
}
declare module 'rambda/benchmarks/pick.js' {
  declare module.exports: $Exports<'rambda/benchmarks/pick'>;
}
declare module 'rambda/benchmarks/prop.js' {
  declare module.exports: $Exports<'rambda/benchmarks/prop'>;
}
declare module 'rambda/benchmarks/propEq.js' {
  declare module.exports: $Exports<'rambda/benchmarks/propEq'>;
}
declare module 'rambda/benchmarks/range.js' {
  declare module.exports: $Exports<'rambda/benchmarks/range'>;
}
declare module 'rambda/benchmarks/reduce.js' {
  declare module.exports: $Exports<'rambda/benchmarks/reduce'>;
}
declare module 'rambda/files/benchmark.js' {
  declare module.exports: $Exports<'rambda/files/benchmark'>;
}
declare module 'rambda/files/browseByTag.js' {
  declare module.exports: $Exports<'rambda/files/browseByTag'>;
}
declare module 'rambda/files/lint.js' {
  declare module.exports: $Exports<'rambda/files/lint'>;
}
declare module 'rambda/files/rollup.config.js' {
  declare module.exports: $Exports<'rambda/files/rollup.config'>;
}
declare module 'rambda/index' {
  declare module.exports: $Exports<'rambda'>;
}
declare module 'rambda/index.js' {
  declare module.exports: $Exports<'rambda'>;
}
declare module 'rambda/modules/addIndex.js' {
  declare module.exports: $Exports<'rambda/modules/addIndex'>;
}
declare module 'rambda/modules/adjust.js' {
  declare module.exports: $Exports<'rambda/modules/adjust'>;
}
declare module 'rambda/modules/all.js' {
  declare module.exports: $Exports<'rambda/modules/all'>;
}
declare module 'rambda/modules/allPass.js' {
  declare module.exports: $Exports<'rambda/modules/allPass'>;
}
declare module 'rambda/modules/any.js' {
  declare module.exports: $Exports<'rambda/modules/any'>;
}
declare module 'rambda/modules/append.js' {
  declare module.exports: $Exports<'rambda/modules/append'>;
}
declare module 'rambda/modules/both.js' {
  declare module.exports: $Exports<'rambda/modules/both'>;
}
declare module 'rambda/modules/compose.js' {
  declare module.exports: $Exports<'rambda/modules/compose'>;
}
declare module 'rambda/modules/contains.js' {
  declare module.exports: $Exports<'rambda/modules/contains'>;
}
declare module 'rambda/modules/curry.js' {
  declare module.exports: $Exports<'rambda/modules/curry'>;
}
declare module 'rambda/modules/defaultTo.js' {
  declare module.exports: $Exports<'rambda/modules/defaultTo'>;
}
declare module 'rambda/modules/drop.js' {
  declare module.exports: $Exports<'rambda/modules/drop'>;
}
declare module 'rambda/modules/dropLast.js' {
  declare module.exports: $Exports<'rambda/modules/dropLast'>;
}
declare module 'rambda/modules/either.js' {
  declare module.exports: $Exports<'rambda/modules/either'>;
}
declare module 'rambda/modules/equals.js' {
  declare module.exports: $Exports<'rambda/modules/equals'>;
}
declare module 'rambda/modules/filter.js' {
  declare module.exports: $Exports<'rambda/modules/filter'>;
}
declare module 'rambda/modules/find.js' {
  declare module.exports: $Exports<'rambda/modules/find'>;
}
declare module 'rambda/modules/findIndex.js' {
  declare module.exports: $Exports<'rambda/modules/findIndex'>;
}
declare module 'rambda/modules/flatten.js' {
  declare module.exports: $Exports<'rambda/modules/flatten'>;
}
declare module 'rambda/modules/has.js' {
  declare module.exports: $Exports<'rambda/modules/has'>;
}
declare module 'rambda/modules/head.js' {
  declare module.exports: $Exports<'rambda/modules/head'>;
}
declare module 'rambda/modules/ifElse.js' {
  declare module.exports: $Exports<'rambda/modules/ifElse'>;
}
declare module 'rambda/modules/indexOf.js' {
  declare module.exports: $Exports<'rambda/modules/indexOf'>;
}
declare module 'rambda/modules/init.js' {
  declare module.exports: $Exports<'rambda/modules/init'>;
}
declare module 'rambda/modules/internal/baseSlice.js' {
  declare module.exports: $Exports<'rambda/modules/internal/baseSlice'>;
}
declare module 'rambda/modules/internal/curry.js' {
  declare module.exports: $Exports<'rambda/modules/internal/curry'>;
}
declare module 'rambda/modules/internal/curryThree.js' {
  declare module.exports: $Exports<'rambda/modules/internal/curryThree'>;
}
declare module 'rambda/modules/internal/helper.js' {
  declare module.exports: $Exports<'rambda/modules/internal/helper'>;
}
declare module 'rambda/modules/internal/mathHelper.js' {
  declare module.exports: $Exports<'rambda/modules/internal/mathHelper'>;
}
declare module 'rambda/modules/internal/oppositeHelper.js' {
  declare module.exports: $Exports<'rambda/modules/internal/oppositeHelper'>;
}
declare module 'rambda/modules/internal/passingHelper.js' {
  declare module.exports: $Exports<'rambda/modules/internal/passingHelper'>;
}
declare module 'rambda/modules/internal/propHelper.js' {
  declare module.exports: $Exports<'rambda/modules/internal/propHelper'>;
}
declare module 'rambda/modules/internal/simpleHelper.js' {
  declare module.exports: $Exports<'rambda/modules/internal/simpleHelper'>;
}
declare module 'rambda/modules/last.js' {
  declare module.exports: $Exports<'rambda/modules/last'>;
}
declare module 'rambda/modules/map.js' {
  declare module.exports: $Exports<'rambda/modules/map'>;
}
declare module 'rambda/modules/match.js' {
  declare module.exports: $Exports<'rambda/modules/match'>;
}
declare module 'rambda/modules/merge.js' {
  declare module.exports: $Exports<'rambda/modules/merge'>;
}
declare module 'rambda/modules/omit.js' {
  declare module.exports: $Exports<'rambda/modules/omit'>;
}
declare module 'rambda/modules/partialCurry.js' {
  declare module.exports: $Exports<'rambda/modules/partialCurry'>;
}
declare module 'rambda/modules/path.js' {
  declare module.exports: $Exports<'rambda/modules/path'>;
}
declare module 'rambda/modules/pick.js' {
  declare module.exports: $Exports<'rambda/modules/pick'>;
}
declare module 'rambda/modules/pluck.js' {
  declare module.exports: $Exports<'rambda/modules/pluck'>;
}
declare module 'rambda/modules/prepend.js' {
  declare module.exports: $Exports<'rambda/modules/prepend'>;
}
declare module 'rambda/modules/prop.js' {
  declare module.exports: $Exports<'rambda/modules/prop'>;
}
declare module 'rambda/modules/propEq.js' {
  declare module.exports: $Exports<'rambda/modules/propEq'>;
}
declare module 'rambda/modules/range.js' {
  declare module.exports: $Exports<'rambda/modules/range'>;
}
declare module 'rambda/modules/reduce.js' {
  declare module.exports: $Exports<'rambda/modules/reduce'>;
}
declare module 'rambda/modules/repeat.js' {
  declare module.exports: $Exports<'rambda/modules/repeat'>;
}
declare module 'rambda/modules/replace.js' {
  declare module.exports: $Exports<'rambda/modules/replace'>;
}
declare module 'rambda/modules/sort.js' {
  declare module.exports: $Exports<'rambda/modules/sort'>;
}
declare module 'rambda/modules/sortBy.js' {
  declare module.exports: $Exports<'rambda/modules/sortBy'>;
}
declare module 'rambda/modules/split.js' {
  declare module.exports: $Exports<'rambda/modules/split'>;
}
declare module 'rambda/modules/splitEvery.js' {
  declare module.exports: $Exports<'rambda/modules/splitEvery'>;
}
declare module 'rambda/modules/tail.js' {
  declare module.exports: $Exports<'rambda/modules/tail'>;
}
declare module 'rambda/modules/take.js' {
  declare module.exports: $Exports<'rambda/modules/take'>;
}
declare module 'rambda/modules/takeLast.js' {
  declare module.exports: $Exports<'rambda/modules/takeLast'>;
}
declare module 'rambda/modules/tap.js' {
  declare module.exports: $Exports<'rambda/modules/tap'>;
}
declare module 'rambda/modules/testFn.js' {
  declare module.exports: $Exports<'rambda/modules/testFn'>;
}
declare module 'rambda/modules/type.js' {
  declare module.exports: $Exports<'rambda/modules/type'>;
}
declare module 'rambda/modules/uniq.js' {
  declare module.exports: $Exports<'rambda/modules/uniq'>;
}
declare module 'rambda/modules/update.js' {
  declare module.exports: $Exports<'rambda/modules/update'>;
}
declare module 'rambda/modules/values.js' {
  declare module.exports: $Exports<'rambda/modules/values'>;
}
declare module 'rambda/rambda.js' {
  declare module.exports: $Exports<'rambda/rambda'>;
}
declare module 'rambda/webVersion.js' {
  declare module.exports: $Exports<'rambda/webVersion'>;
}
